package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"cute-todo-api/graph/model"
	"fmt"

	_ "github.com/lib/pq"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, title string, priority string) (*model.Task, error) {
	t := &model.Task{}
	err := r.DB.QueryRowContext(ctx,
		`INSERT INTO tasks (title, priority) VALUES ($1, $2)
         RETURNING id, title, status, priority, created_at`,
		title, priority,
	).Scan(&t.ID, &t.Title, &t.Status, &t.Priority, &t.CreatedAt)
	return t, err
}

// UpdateStatus is the resolver for the updateStatus field.
func (r *mutationResolver) UpdateStatus(ctx context.Context, id string, status string) (*model.Task, error) {
	t := &model.Task{}
	err := r.DB.QueryRowContext(ctx,
		`UPDATE tasks SET status=$1 WHERE id=$2
         RETURNING id, title, status, priority, created_at`,
		status, id,
	).Scan(&t.ID, &t.Title, &t.Status, &t.Priority, &t.CreatedAt)
	return t, err
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	rows, err := r.DB.QueryContext(ctx,
		`SELECT id, title, status, priority, created_at FROM tasks ORDER BY created_at DESC`,
	)
	if err != nil {
		return nil, fmt.Errorf("db query failed: %w", err)
	}
	defer rows.Close()

	var tasks []*model.Task
	for rows.Next() {
		t := &model.Task{}
		if err := rows.Scan(&t.ID, &t.Title, &t.Status, &t.Priority, &t.CreatedAt); err != nil {
			return nil, err
		}
		tasks = append(tasks, t)
	}
	return tasks, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	t := &model.Task{}
	err := r.DB.QueryRowContext(ctx,
		`SELECT id, title, status, priority, created_at FROM tasks WHERE id=$1`,
		id,
	).Scan(&t.ID, &t.Title, &t.Status, &t.Priority, &t.CreatedAt)
	return t, err
}
// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
